### ISSUE TITLE
Readme.md

### ISSUE THREAD

**Issue by shalookumari** [99003612/SDLC_LTTS#10]
THE 4 W’S and one H
•	WHY? The system is able to calculate loans very easily and plus it is very handy.
•	WHAT?  There is a requirement of loan when anyone do not have enough money thus the system can be used before. 
•	WHEN? The system can be used anytime.
•	WHERE? The system is beneficial for bank related purpose.
•	HOW? The system requires certain documents like id proof, bank statement etc for verification before taking loan.

THE HIGH LEVEL REQUIREMENTS
•	CIBIL score as the summary of credit history.
•	Eligibility criteria like gross income, loan tenure, interest rate.
 
THE LOW LEVEL REQUIREMENTS
•	To set total loan period in months
•	To set the initial amount.
•	Calculate the initial loan amount, given: monthly payment, loan period and interest,loan balance after making several payments, the loan interest given: (Interest Rate / number of Payments) *Loan principle.
•	Customer need to set the yearly interest rate, the elapsed period in months, fees for opening the loan, set monthly loan payment.

FEASIBILITY STUDY
Technical Feasibility
•	The project has a detailed design for the system and all the tools required to build the project are available for free.
•	The system is being developed in C++ programming language.
        Visual Studio Code
•	Visual Studio Code is an editor first, and includes the features you need for highly productive source code editing. Visual 
        Studio Code is a free source-code editor made by Microsoft for Windows, Linux and macOS.
•	It comes with built-in support for JavaScript, Typescript and Node.js and has a rich ecosystem of extensions for other 
        languages (such as C++, C#, Java, Python, PHP, Go) and runtimes (such as .NET and Unity).
Operational Feasibility
•	In terms of hardware components, a machine is required which can meet the requirements and has sufficient storage space 
        to execute the code. 
•	For Software requirements, C++ support for Visual Studio Code is provided by a Microsoft C++ extension to enable cross- 
        platform C++ development on Windows, Linux, and macOS.
Economic feasibility
•	Cost efficient as it requires very less amount of money.

SWOT ANALYSIS
STRENGTHS
•	Less time consuming
•	Easy to use
•	No need of calculations
•	Less chances of error
•	Versatile loans
•	No need to maintain bulk of papers.
•	Can be done remotely.

WEAKNESS:
•	High fees and penalties.
•	High monthly payments.
•	Interest rates are higher than home loans.
•	Facing of higher debts on no payment of loans.

OPPORTUNITIES:
•	Increase in market demand as a lot of people loan as financial help.
•	Rise in revenues.
•	New technologies can be added in future with new updates.

THREATS:
•	Hardware/software failures.
•	Leakage of personal information as important documents require personal data that must be handled with care.
•	False document possibility as may be some people submit come up with false identity.
•	Storage issue as it requires a lot of memory to store all data in a big amount.

Software Requirements Specification 
•	Customers Details
•	Cash details
•	Bank Details

User Requirements
•	View payable Interest
•	View Loan EMI
•	View total payable amount (interest + Principal)
•	View Documents required
•	Upload Documents
•	Documents Verification

 Non Functional Requirements
i.	Reliable
ii.	Usability
iii.	Availability

External Interfaces Required
i.	System Evolution
ii.	Supplementary Evolution

**Comment by 99003612** [comment]
Good work. Thank you.
