### ISSUE TITLE
CIBIL Score Workflow

### ISSUE THREAD

**Issue by kricha-24** [99003612/SDLC_LTTS#11]
Prior to loan application, every applicant has to verify CIBIL Score. Loan application will be rejected if the CIBIL Score is greater than or equals to 300. Only if the score if smaller than equals to 900, applicant will be able to proceed further and will be eligible to apply for a loan, either Personal or Home Loan. Once the CIBIL Score if verified and accepted, applicant can upload all the required documents, and apply for the loan successfully.
![Workflow](https://user-images.githubusercontent.com/78844495/107792909-b4673600-6d7b-11eb-8c88-5e4e30553566.png)

**Comment by 99003612** [comment]
Description of CIBIL Score
