### ISSUE TITLE
Readme.md

### ISSUE THREAD

**Issue by shalookumari** [99003612/SDLC_LTTS#7]
The 4 W’S Of Loan Calculator
•	WHY? 
We need a handy calculator to calculate a personal loan like a home loan or a car loan because it is very lengthy and time consuming.
•	WHAT?
Sometimes there is a need for personal loans like home loan or a car loan as sometimes people do not have sufficient amount of money to buy a home or a car, so this loan calculator will help them to calculate the loan even before taking the loan. 
•	WHEN?

As it is easily available and easy to access thus can be used 24 hours throughout the day on any day of a week
•	WHERE?

The calculation of loan is required and can be done in banks specially as they are the biggest and official provider of loans and provide all kinds of loans from house loan to car loan.
•	HOW?

To apply for a personal loan like home loan or car loan we should have an income certificate or an employee with certain annual balance,Identity proof (copy of passport/voter id),Address proof (Aadhaar Card),bank statement of previous 3 months.latest salary slips/Current dated salary certificate with the latest form 16 or Income-Tax Return

**Comment by 99003612** [comment]
Okay, will merge!
