### ISSUE TITLE
Readme.md

### ISSUE THREAD

**Issue by khanith** [99003612/SDLC_LTTS#8]
Description: 
1. It is  a sequence diagram explaining how to put loan request by the customer 
2. Describing about the work  of a loan officer to a system.
3. Describing about the responsibilities of a loan officer like checking eligibility ,documentation like pan card and address proof(Aadhaar card).
4. Describes how the loan is granted to a customer.
![SequenceDiagram1](https://user-images.githubusercontent.com/49386930/107736363-e0f16280-6d27-11eb-8902-edbb06a6179c.jpg)

**Comment by 99003612** [comment]
Will implement it in the project.
