### ISSUE TITLE
Readme.md

### ISSUE THREAD

**Issue by akashsinghx** [99003612/SDLC_LTTS#9]
This is the class diagram which shows the various step which are interconnected or interlinked to each other on the basis of dependences as shown :
A ) Customers details like (customer id, customer, name, state and zip).
B ) Loan officer
C ) CIBIL score (high or low) if low then reject
D ) If high then all documents are verified like( Pan card, Address proof)
E ) System approve loan
>Loan credit in the account
![classdiagram1](https://user-images.githubusercontent.com/32004729/107736300-c323fd80-6d27-11eb-85ef-1b8a2895d696.png)

**Comment by 99003612** [comment]
will incorporate the above details in the design phase.
